version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: education_spaces_db
    environment:
      POSTGRES_DB: education_spaces_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - space-network

  sonarqube-db:
    image: postgres:15-alpine
    container_name: sonarqube-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_postgres_data:/var/lib/postgresql/data
    networks:
      - sonarqube-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar" ]
      interval: 10s
      timeout: 5s
      retries: 5

    # SonarQube Server
    sonarqube:
      image: sonarqube:10.4-community
      container_name: sonarqube
      restart: unless-stopped
      depends_on:
        sonarqube-db:
          condition: service_healthy
      environment:
        SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
        SONAR_JDBC_USERNAME: sonar
        SONAR_JDBC_PASSWORD: sonar
        SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
      ports:
        - "9000:9000"
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
      networks:
        - sonarqube-network
      ulimits:
        nofile:
          soft: 65536
          hard: 65536

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space_management_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/education_spaces_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySecretKeyForEducationSpaceManagementSystemThatIsLongEnough
    ports:
      - "8080:8080"
    networks:
      - space-network

volumes:
  postgres_data:
  sonarqube_postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
networks:
  space-network:
    driver: bridge
  sonarqube-network:
    driver: bridge